using System;
using System.Windows;
using System.Windows.Controls;

namespace ICSharpCode.ILSpy.Metadata
{
	/// <summary>
	/// Interaction logic for MetadataTableViews.xaml
	/// </summary>
	public sealed partial class MetadataTableViews
	{
		public MetadataTableViews()
		{
			InitializeComponent();
		}

		static MetadataTableViews instance;

		public static MetadataTableViews Instance {
			get { return instance ??= new MetadataTableViews(); }
		}

		private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
		{
			Helpers.View_AutoGeneratedColumns(sender, e);
		}

		private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
		{
			Helpers.View_AutoGeneratingColumn(sender, e);
		}
	}
}
